[package]
name = "temprec"
version = "0.2.0"
authors = ["Bernd Amend <bernd.amend@gmail.com>"]
edition = '2018'

[dependencies]
regex = "*"
chrono = "*"
rocket = "*"
rocket_codegen = "*"
dht22_pi = "*"
rusqlite = { version = "*", features = ["chrono"]}